config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/awm:
      branch: v0.4.0
      repo: https://github.com/grycap/awm
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/awm git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-saffron-walrus.sh
        container: qc.acc_bluesy-tangerine-bison
  QC.Doc:
    repos:
      github.com/grycap/awm find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-asparagus-dragonfly.sh
        container: qc.doc_surly-puce-saola
      github.com/grycap/awm git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-beige-cat.sh
        container: qc.doc_sloppy-blue-toad
      github.com/grycap/awm markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-tan-woodpecker.sh
        container: qc.doc_homey-salmon-wasp
  QC.Lic:
    repos:
      github.com/grycap/awm licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-auburn-rabbit.sh
        container: qc.lic_scaly-charcoal-bandicoot
  QC.Met:
    repos:
      github.com/grycap/awm validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-auburn-coral.sh
        container: qc.met_fuzzy-purple-worm
  QC.Sec:
    repos:
      github.com/grycap/awm bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-ruby-eel.sh
        container: qc.sec_nippy-indigo-otter
  QC.Sty:
    repos:
      github.com/grycap/awm flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-scarlet-oriole.sh
        container: qc.sty_crappy-magnolia-capybara
      github.com/grycap/awm hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-harlequin-husky.sh
        container: qc.sty_slaphappy-brown-tamarin
      github.com/grycap/awm jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-charcoal-yak.sh
        container: qc.sty_homey-pear-ferret
  QC.Uni:
    repos:
      github.com/grycap/awm commands:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-silver-bison.sh
        container: qc.uni_paltry-plum-tapir
  QC.Ver:
    repos:
      github.com/grycap/awm get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-russet-wolverine.sh
        container: qc.ver_fuzzy-puce-turkey
timeout: 5400
