config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/awm:
      branch: v0.3.0
      repo: https://github.com/grycap/awm
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/awm git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-wheat-cougar.sh
        container: qc.acc_wiggy-chocolate-macaw
  QC.Doc:
    repos:
      github.com/grycap/awm find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cyan-budgerigar.sh
        container: qc.doc_wiggy-saffron-fox
      github.com/grycap/awm git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cerulean-grouse.sh
        container: qc.doc_stinky-amethyst-chicken
      github.com/grycap/awm markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-grey-maltese.sh
        container: qc.doc_snoopy-wheat-weasel
  QC.Lic:
    repos:
      github.com/grycap/awm licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-burgundy-dhole.sh
        container: qc.lic_lanky-tangerine-chinook
  QC.Met:
    repos:
      github.com/grycap/awm validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-violet-coyote.sh
        container: qc.met_craggy-asparagus-indri
  QC.Sec:
    repos:
      github.com/grycap/awm bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-scarlet-birman.sh
        container: qc.sec_wimpy-khaki-moth
  QC.Sty:
    repos:
      github.com/grycap/awm flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-indigo-cattle.sh
        container: qc.sty_crabby-pumpkin-heron
      github.com/grycap/awm hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-teal-lionfish.sh
        container: qc.sty_dorky-crimson-caterpillar
      github.com/grycap/awm jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-olive-russel.sh
        container: qc.sty_snoopy-gold-flamingo
  QC.Uni:
    repos:
      github.com/grycap/awm commands:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-burgundy-macaque.sh
        container: qc.uni_whiny-orchid-zonkey
  QC.Ver:
    repos:
      github.com/grycap/awm get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-viridian-jellyfish.sh
        container: qc.ver_stinky-pear-liger
timeout: 5400
